backend:
  name: git-gateway
  branch: master

media_folder: "assets/images/"
public_folder: "assets/images/"
site_url: "https://food.erikprice.net"

publish_mode: editorial_workflow

collections:
  - label: "Recipe"
    name: "recipe"
    folder: "_posts/"
    create: true
    extension: "md"
    editor:
      preview: true
    slug: "{year}-{month}-{day}-{slug}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Description", 
        name: "description", 
        widget: "markdown", 
        required: false 
        minimal: true
      - { label: "Source URL", name: "via_url", widget: "string", required: false }
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        field: { label: "Ingredient", name: "ingredient", widget: "string" }
      - label: "Instructions"
        name: "instructions"
        widget: "list"
        field: { label: "Step", name: "step", widget: "text" }
